#main accounts token
mainToken = "ODUyMjE4NzgwNTk5OTc1OTQ2.YhuQQQ.eftdVKA28L5BMHJNcsoNx-ovNDs"
# claim the sniped nitros on main account, if false nitro will be claimed on whichever token sniped it
claimOnMain = true
# check messages on main account
snipeOnMain = true
# alt accounts tokens
altTokens = ["OTA3NTgwMDAyNDM3MDUwMzk4.YhuCUg.3cmNzg51JlrWwPp_L1hAYrS8Z18", "ODk2NDAzOTQxNzMzMDU2NTMy.YhuO-A.snihpC2HVtHVU2MRjDSdexv1gyY", "NzUzODY1MzQ4NjcxMDc4NDgx.YhuFhQ.fjBB-5OiDT_e18t0Bqvq1WrYZsI", "NzQwMTgyOTk1NTYyMTM1NTU0.YhueTA.-sMnzriBrs38cMFnRl-l5LE5oe8"]
#use alts to snipe
useAlts = true

#snipe pastes
snipePastes = true
#save paste content
savePastes = true
#if snipe-pastes is true, the paste tools that are set to true will be sniped
#supported pastes:
#"safenote.co", "controlc.com", "commie.io", "vpaste.net",
#"ivpaste.com", "justpaste.it", "apaste.info", "ghostbin.com",
#"ghostbin.co", "secureshare.support", "1ty.me", "quickforget.com",
#"temp.pm", "privatty.com", "saltify.io", "onetimesecret.com", "revealit.me",
#"pastebin.com", "anonfiles.com", "hatebin.com", "gofile.io", "paste2.org",
#"slexy.org", "pastelink.net", "paste.org.ru", "dumpz.org",
#"heypasteit.com", "paste.centos.org", "paste.ee", "paste.ofcode.org",
#"justpaste.me"
pasteTools = [
  "safenote.co",
  "controlc.com",
  "commie.io",
  "vpaste.net",
  "ivpaste.com",
  "justpaste.it",
  "apaste.info",
  "ghostbin.com",
  "ghostbin.co",
  "secureshare.support",
  "1ty.me",
  "quickforget.com",
  "temp.pm",
  "privatty.com",
  "saltify.io",
  "onetimesecret.com",
  "revealit.me",
  "pastebin.com",
  "anonfiles.com",
  "hatebin.com",
  "gofile.io",
  "paste2.org",
  "slexy.org",
  "pastelink.net",
  "paste.org.ru",
  "dumpz.org",
  "heypasteit.com",
  "paste.centos.org",
  "paste.ee",
  "paste.ofcode.org",
  "justpaste.me"
]

#custom webhook sent after one a the following events
webhookGiveawayJoined = "https://discord.com/api/webhooks/947159796451278908/C6qbd7mJ-lExD-VterKBAR4QAQUWQMAsZeaZiiGZ4KAhpqU7BC8bHr6FHTCoT1Y8lQfW"
webhookSentGiveawayDM = "https://discord.com/api/webhooks/947159648253919233/21hqDJoV8nRPZgEuMGjvxk_kiatwmbqrfegAL_Jwi3VP50b4vO75so5b5m2fSOwlU-TQ"
webhookGiveawayWon = "https://discord.com/api/webhooks/947159896787410995/6l8yULHAUrDYm8zxZITx8T70cqxSjUDaxixKbGz6vRCM0R64RuXfHF1LBnaX_YY1Pw2w"
webhookNitroFailed = "https://discord.com/api/webhooks/947159989145993276/vXCyRbHAHWFAGYXaFjCk1M93-0EgGwr0llIO3KQIcgh7VUED1jfGPd7jY9z1fd8_cpfR"
webhookNitroClaimed = "https://discord.com/api/webhooks/947160063594876948/7FGp8ODG5DXuZ1R3P14AOMZwksOcQLInO8vkdtMXGfAlXJj0BG0zcsBoj4T4o3YAMA53"

pingOnSuccess = true

#show scraped invites
showScrapedInvites = true
#save scraped invites
saveScrapedInvites = true

#join giveaways
joinGiveaways = true
#join giveaways on alts only
joinGiveawaysAltsOnly = false
#join giveaways after this many seconds, 0 for instant
joinGiveawaysDelay = 1
#auto claim giveaway
autoClaimGiveaway = true
#auto claim delay, will send message after this many seconds
autoClaimDelay = 3
#auto claim giveaway message
autoclaimGiveawayMessage = "hey i won the giveaway"
#dont join giveaways that contain these words
blacklistWordsGiveaway = ["ban","sniper/selfbot", "test","sniper","selfbot"]
#ONLY join giveaways that contain these words (case insensitive)
whitelistWordsGiveaway = ["nitro"]

#if removeDuplicates=true, nitro codes will be saved and won't be checked again
removeDuplicates = true
showDuplicates = true

#Optical Character Recognition, will snipe nitro code in images
OCR = true
#will snipe nitro code in QRCodes
QRCode = true

# if removeDuplicatesGuild=true, it will ask you if you want leave duplicate guilds on alts on start
removeDuplicatesGuilds = true

# type .stats in any channel to see sniper stats
webhookStats = true
# Send stats to this webhook
webhookStatsLink = "https://discord.com/api/webhooks/947487749374631936/IT0QopwQjbArve3rOJ9rxoin8BFXQULBrXRUMdmS-7anYlSZ3e0bSXlLKTZ8PhleeF5v"
# Custom stat command
webhookStatsCommand = ".stats"

# Try to redeem words that looks like Nitro gift code
smartSnipe = true